# Generated by Django 2.1.1 on 2018-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('game_date', models.DateTimeField(verbose_name='date')),
                ('zone_name', models.CharField(max_length=30)),
                ('zone_level', models.IntegerField()),
                ('end_text', models.CharField(max_length=300)),
            ],
        ),
    ]
