# Generated by Django 2.1.1 on 2018-09-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_gamelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelog',
            name='end_text',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='game_date',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='zone_level',
        ),
        migrations.RemoveField(
            model_name='gamelog',
            name='zone_name',
        ),
    ]
