# Generated by Django 2.1.1 on 2018-09-01 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20180901_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='date'),
        ),
    ]
