# Generated by Django 2.1.1 on 2018-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_gamelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date'),
        ),
    ]
