# Generated by Django 2.1.1 on 2018-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180901_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='end_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
