# Generated by Django 2.1.1 on 2018-09-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_gamelog_end_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelog',
            name='zone_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='zone_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
