# Generated by Django 2.1.1 on 2018-09-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20180901_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelog',
            old_name='player_name',
            new_name='playerName',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='end_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='zone_level',
            new_name='zoneLevel',
        ),
        migrations.RenameField(
            model_name='gamelog',
            old_name='zone_name',
            new_name='zoneName',
        ),
        migrations.AddField(
            model_name='gamelog',
            name='playerClass',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='playerLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='time',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
